control-plane:
  replicaCount: 1
  image:
    repository: crpi-jok0hxci4hqtytw8.cn-shenzhen.personal.cr.aliyuncs.com/djy-repository/operator
    tag: b2c5264
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
data-plane:
  replicaCount: 1
  image:
    repository: crpi-jok0hxci4hqtytw8.cn-shenzhen.personal.cr.aliyuncs.com/djy-repository/dataplane
    tag: a96d38d
  controlPlane:
    # 依赖控制面 Service 的名称，实现联动
    endpoint: "operator-controller-manager.{{ .Release.Namespace }}.svc:50051"
  otel:
    endpoint: "jaeger-collector.istio-system.svc.cluster.local:4317"
  resources:
    limits:
      cpu: 800m
      memory: 512Mi
    requests:
      cpu: 400m
      memory: 256Mi
dataPlane:
  image:
    tag: b2c5264
