# syntax=docker/dockerfile:1.4
# build golang image with go version 1.25.5
FROM golang:1.26.5 AS builder

# build parameters
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# set work directory
WORKDIR /app
# copy go mod and go sum files
COPY go.mod go.sum ./
# download go mod dependencies
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

# copy source files
COPY . .
# build the binary
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -mod=readonly -ldflags="-s -w" -o llm-router ./main/llm-router.go


FROM alpine:latest AS run
WORKDIR /app
COPY --from=builder /app/llm-router /app/llm-router

ENV CONTROL_PLANE_ENDPOINT="localhost:50051" \
    OTEL_EXPORTER_OTLP_ENDPOINT="localhost:4317"

# create user and user group, use fix UID/GID 1001
RUN addgroup -g 1001 appgroup && \
    adduser -u 1001 -G appgroup -D appuser
# setup workdir owner [user:group]
RUN chown -R appuser:appgroup /app
# default startup user
USER 1001





EXPOSE 8080 9090
CMD ["./llm-router"]



