apiVersion: v1
kind: Service
metadata:
  name: operator-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: operator
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: operator
  ports:
    - name: grpc-xds
      port: 50051
      targetPort: 50051
      protocol: TCP