apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-deployment
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - branch: master
            env: prod
            namespace: prod-llm-router
            uri: https://kubernetes.default.svc
          # - branch: dev
          #   env: dev
          #   namespace: dev-llm-router
          #   uri: https://kubernetes.default.svc
  template:
    metadata:
      name: 'llm-gateway-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'git@github.com:duuuuu17/Gateway.git'
        targetRevision: '{{branch}}'
        path: k8s/helm/gateway-umbrella
        helm:
          # 如果需要在 ApplicationSet 层面覆盖命名空间等参数，可以在这里写
          valueFiles: 
            - '{{env}}-values.yaml'
      destination:
        server: '{{uri}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true       # 如果在 Git 里删了资源，集群里也删
          selfHeal: true    # 如果有人手动改了集群资源，自动恢复成 Git 的状态
        syncOptions:
          - CreateNamespace=true