apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-deployment
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - branch: master
            env: prod
            namespace: prod-llm-router
            uri: https://kubernetes.default.svc
          # - branch: dev
          #   env: dev
          #   namespace: dev-llm-router
          #   uri: https://kubernetes.default.svc
  template:
    metadata:
      name: 'llm-gateway-{{env}}'
    spec:
      #  忽略cert-manager资源的status字段，避免因为Argo CD配置的selfHeal自愈触发过快，
      # 强制PATCH cert-manager资源，导致cert-manager Operator发现资源版本改变触发重试修改Status，进入死循环
      ignoreDifferences:
        - group: cert-manager.io
          kind: Certificate
          namespace: '{{namespace}}'
          jsonPointers:
            - /status
        - group: cert-manager.io
          kind: CertificateRequest
          namespace: '{{namespace}}'
          jsonPointers:
            - /status
      project: default
      source:
        repoURL: 'git@github.com:duuuuu17/Gateway.git'
        targetRevision: '{{branch}}'
        path: k8s/helm/gateway-umbrella
        helm:
          # 如果需要在 ApplicationSet 层面覆盖命名空间等参数，可以在这里写
          valueFiles: 
            - '{{env}}-values.yaml'
      destination:
        server: '{{uri}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true       # 如果在 Git 里删了资源，集群里也删
          selfHeal: true    # 如果有人手动改了集群资源，自动恢复成 Git 的状态
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true # 建议加上，防止Webhook未就绪时DryRun报错
# Note: ApplicationSet must install in the namespace argocd