---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - config.llm-router.example.io
  resources:
  - llmrouterconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.llm-router.example.io
  resources:
  - llmrouterconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - config.llm-router.example.io
  resources:
  - llmrouterconfigs/status
  verbs:
  - get
  - patch
  - update
