apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-dataplane.fullname" . }}
  labels:
    {{- include "gateway-dataplane.labels" . | nindent 4 }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      {{- if .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      {{- if .Values.service.metricsNodePort }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}
      name: metrics
  selector:
    {{- include "gateway-dataplane.selectorLabels" . | nindent 4 }}
