// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: llmrouter-xds.proto

package llmrouterxds

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 由Data Plane发送初始请求或ACK
type DiscoveryRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo string                 `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// 关键字段：资源类型
	TypeUrl string `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"` // type.googleapis.com.llmrouter.xds.v1alpha1.<CDS/EDS/RDS-name>
	// 订阅的 service 名
	ResourceNames []string `protobuf:"bytes,3,rep,name=resource_names,json=resourceNames,proto3" json:"resource_names,omitempty"`
	// 数据面实例ID
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 控制面给定数据面使用的nonce，防止重放
	ResponseNonce string `protobuf:"bytes,5,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	ErrorDetail   string `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_llmrouter_xds_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoveryRequest) GetVersionInfo() string {
	if x != nil {
		return x.VersionInfo
	}
	return ""
}

func (x *DiscoveryRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DiscoveryRequest) GetResourceNames() []string {
	if x != nil {
		return x.ResourceNames
	}
	return nil
}

func (x *DiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DiscoveryRequest) GetResponseNonce() string {
	if x != nil {
		return x.ResponseNonce
	}
	return ""
}

func (x *DiscoveryRequest) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

// 由Control Plane 推送
type DiscoveryResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	VersionInfo string                 `protobuf:"bytes,1,opt,name=version_info,json=versionInfo,proto3" json:"version_info,omitempty"`
	// 关键字段：资源类型
	TypeUrl string `protobuf:"bytes,2,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// 订阅的 service 名
	Resources       []*anypb.Any `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	RemoveResources []string     `protobuf:"bytes,4,rep,name=remove_resources,json=removeResources,proto3" json:"remove_resources,omitempty"`
	// 避免重放
	Nonce         string `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_llmrouter_xds_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResponse) GetVersionInfo() string {
	if x != nil {
		return x.VersionInfo
	}
	return ""
}

func (x *DiscoveryResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DiscoveryResponse) GetResources() []*anypb.Any {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DiscoveryResponse) GetRemoveResources() []string {
	if x != nil {
		return x.RemoveResources
	}
	return nil
}

func (x *DiscoveryResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// ==========================================
// 具体资源定义 (Data Transfer Object - DTO)
// ==========================================
// CDS
type LLMRouterCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Models        []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	Protocols     []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Streaming     bool                   `protobuf:"varint,4,opt,name=streaming,proto3" json:"streaming,omitempty"`
	LbStrategy    string                 `protobuf:"bytes,5,opt,name=lb_strategy,json=lbStrategy,proto3" json:"lb_strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRouterCluster) Reset() {
	*x = LLMRouterCluster{}
	mi := &file_llmrouter_xds_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterCluster) ProtoMessage() {}

func (x *LLMRouterCluster) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterCluster.ProtoReflect.Descriptor instead.
func (*LLMRouterCluster) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{2}
}

func (x *LLMRouterCluster) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMRouterCluster) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *LLMRouterCluster) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *LLMRouterCluster) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *LLMRouterCluster) GetLbStrategy() string {
	if x != nil {
		return x.LbStrategy
	}
	return ""
}

// EDS
type LLMRouterEndpointAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Endpoints     []*LLMRouterEndpoint   `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRouterEndpointAssignment) Reset() {
	*x = LLMRouterEndpointAssignment{}
	mi := &file_llmrouter_xds_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterEndpointAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterEndpointAssignment) ProtoMessage() {}

func (x *LLMRouterEndpointAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterEndpointAssignment.ProtoReflect.Descriptor instead.
func (*LLMRouterEndpointAssignment) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{3}
}

func (x *LLMRouterEndpointAssignment) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LLMRouterEndpointAssignment) GetEndpoints() []*LLMRouterEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type LLMRouterEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRouterEndpoint) Reset() {
	*x = LLMRouterEndpoint{}
	mi := &file_llmrouter_xds_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterEndpoint) ProtoMessage() {}

func (x *LLMRouterEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterEndpoint.ProtoReflect.Descriptor instead.
func (*LLMRouterEndpoint) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{4}
}

func (x *LLMRouterEndpoint) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// RDS
type LLMRouterRouting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterName   string                 `protobuf:"bytes,1,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRouterRouting) Reset() {
	*x = LLMRouterRouting{}
	mi := &file_llmrouter_xds_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterRouting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterRouting) ProtoMessage() {}

func (x *LLMRouterRouting) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterRouting.ProtoReflect.Descriptor instead.
func (*LLMRouterRouting) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{5}
}

func (x *LLMRouterRouting) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *LLMRouterRouting) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *LLMRouterRouting) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *LLMRouterRouting) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// TDS
type LLMRouterTenantPipelineConfig struct {
	state             protoimpl.MessageState         `protogen:"open.v1"`
	TenantId          string                         `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Enabled           bool                           `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	TenantPreRouting  []*LLMRouterTenantPipelineStep `protobuf:"bytes,3,rep,name=tenant_pre_routing,json=tenantPreRouting,proto3" json:"tenant_pre_routing,omitempty"`
	TenantPostRouting []*LLMRouterTenantPipelineStep `protobuf:"bytes,4,rep,name=tenant_post_routing,json=tenantPostRouting,proto3" json:"tenant_post_routing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LLMRouterTenantPipelineConfig) Reset() {
	*x = LLMRouterTenantPipelineConfig{}
	mi := &file_llmrouter_xds_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterTenantPipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterTenantPipelineConfig) ProtoMessage() {}

func (x *LLMRouterTenantPipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterTenantPipelineConfig.ProtoReflect.Descriptor instead.
func (*LLMRouterTenantPipelineConfig) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{6}
}

func (x *LLMRouterTenantPipelineConfig) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LLMRouterTenantPipelineConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LLMRouterTenantPipelineConfig) GetTenantPreRouting() []*LLMRouterTenantPipelineStep {
	if x != nil {
		return x.TenantPreRouting
	}
	return nil
}

func (x *LLMRouterTenantPipelineConfig) GetTenantPostRouting() []*LLMRouterTenantPipelineStep {
	if x != nil {
		return x.TenantPostRouting
	}
	return nil
}

type LLMRouterTenantPipelineStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"` // struct类型本身包含多种基本结构类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRouterTenantPipelineStep) Reset() {
	*x = LLMRouterTenantPipelineStep{}
	mi := &file_llmrouter_xds_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRouterTenantPipelineStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRouterTenantPipelineStep) ProtoMessage() {}

func (x *LLMRouterTenantPipelineStep) ProtoReflect() protoreflect.Message {
	mi := &file_llmrouter_xds_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRouterTenantPipelineStep.ProtoReflect.Descriptor instead.
func (*LLMRouterTenantPipelineStep) Descriptor() ([]byte, []int) {
	return file_llmrouter_xds_proto_rawDescGZIP(), []int{7}
}

func (x *LLMRouterTenantPipelineStep) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *LLMRouterTenantPipelineStep) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_llmrouter_xds_proto protoreflect.FileDescriptor

const file_llmrouter_xds_proto_rawDesc = "" +
	"\n" +
	"\x13llmrouter-xds.proto\x12\x16llmrouter.xds.v1alpha1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xda\x01\n" +
	"\x10DiscoveryRequest\x12!\n" +
	"\fversion_info\x18\x01 \x01(\tR\vversionInfo\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x12%\n" +
	"\x0eresource_names\x18\x03 \x03(\tR\rresourceNames\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eresponse_nonce\x18\x05 \x01(\tR\rresponseNonce\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\tR\verrorDetail\"\xc6\x01\n" +
	"\x11DiscoveryResponse\x12!\n" +
	"\fversion_info\x18\x01 \x01(\tR\vversionInfo\x12\x19\n" +
	"\btype_url\x18\x02 \x01(\tR\atypeUrl\x122\n" +
	"\tresources\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\tresources\x12)\n" +
	"\x10remove_resources\x18\x04 \x03(\tR\x0fremoveResources\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\tR\x05nonce\"\x9b\x01\n" +
	"\x10LLMRouterCluster\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x1c\n" +
	"\tstreaming\x18\x04 \x01(\bR\tstreaming\x12\x1f\n" +
	"\vlb_strategy\x18\x05 \x01(\tR\n" +
	"lbStrategy\"\x89\x01\n" +
	"\x1bLLMRouterEndpointAssignment\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12G\n" +
	"\tendpoints\x18\x02 \x03(\v2).llmrouter.xds.v1alpha1.LLMRouterEndpointR\tendpoints\"-\n" +
	"\x11LLMRouterEndpoint\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x81\x01\n" +
	"\x10LLMRouterRouting\x12!\n" +
	"\fcluster_name\x18\x01 \x01(\tR\vclusterName\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"\x9e\x02\n" +
	"\x1dLLMRouterTenantPipelineConfig\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12a\n" +
	"\x12tenant_pre_routing\x18\x03 \x03(\v23.llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStepR\x10tenantPreRouting\x12c\n" +
	"\x13tenant_post_routing\x18\x04 \x03(\v23.llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStepR\x11tenantPostRouting\"o\n" +
	"\x1bLLMRouterTenantPipelineStep\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config2\x92\x01\n" +
	"\x1aAggregatedDiscoveryService\x12t\n" +
	"\x19StreamAggregatedResources\x12(.llmrouter.xds.v1alpha1.DiscoveryRequest\x1a).llmrouter.xds.v1alpha1.DiscoveryResponse(\x010\x01B\x1dZ\x1b./llmrouterxds;llmrouterxdsb\x06proto3"

var (
	file_llmrouter_xds_proto_rawDescOnce sync.Once
	file_llmrouter_xds_proto_rawDescData []byte
)

func file_llmrouter_xds_proto_rawDescGZIP() []byte {
	file_llmrouter_xds_proto_rawDescOnce.Do(func() {
		file_llmrouter_xds_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmrouter_xds_proto_rawDesc), len(file_llmrouter_xds_proto_rawDesc)))
	})
	return file_llmrouter_xds_proto_rawDescData
}

var file_llmrouter_xds_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_llmrouter_xds_proto_goTypes = []any{
	(*DiscoveryRequest)(nil),              // 0: llmrouter.xds.v1alpha1.DiscoveryRequest
	(*DiscoveryResponse)(nil),             // 1: llmrouter.xds.v1alpha1.DiscoveryResponse
	(*LLMRouterCluster)(nil),              // 2: llmrouter.xds.v1alpha1.LLMRouterCluster
	(*LLMRouterEndpointAssignment)(nil),   // 3: llmrouter.xds.v1alpha1.LLMRouterEndpointAssignment
	(*LLMRouterEndpoint)(nil),             // 4: llmrouter.xds.v1alpha1.LLMRouterEndpoint
	(*LLMRouterRouting)(nil),              // 5: llmrouter.xds.v1alpha1.LLMRouterRouting
	(*LLMRouterTenantPipelineConfig)(nil), // 6: llmrouter.xds.v1alpha1.LLMRouterTenantPipelineConfig
	(*LLMRouterTenantPipelineStep)(nil),   // 7: llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStep
	(*anypb.Any)(nil),                     // 8: google.protobuf.Any
	(*structpb.Struct)(nil),               // 9: google.protobuf.Struct
}
var file_llmrouter_xds_proto_depIdxs = []int32{
	8, // 0: llmrouter.xds.v1alpha1.DiscoveryResponse.resources:type_name -> google.protobuf.Any
	4, // 1: llmrouter.xds.v1alpha1.LLMRouterEndpointAssignment.endpoints:type_name -> llmrouter.xds.v1alpha1.LLMRouterEndpoint
	7, // 2: llmrouter.xds.v1alpha1.LLMRouterTenantPipelineConfig.tenant_pre_routing:type_name -> llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStep
	7, // 3: llmrouter.xds.v1alpha1.LLMRouterTenantPipelineConfig.tenant_post_routing:type_name -> llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStep
	9, // 4: llmrouter.xds.v1alpha1.LLMRouterTenantPipelineStep.config:type_name -> google.protobuf.Struct
	0, // 5: llmrouter.xds.v1alpha1.AggregatedDiscoveryService.StreamAggregatedResources:input_type -> llmrouter.xds.v1alpha1.DiscoveryRequest
	1, // 6: llmrouter.xds.v1alpha1.AggregatedDiscoveryService.StreamAggregatedResources:output_type -> llmrouter.xds.v1alpha1.DiscoveryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_llmrouter_xds_proto_init() }
func file_llmrouter_xds_proto_init() {
	if File_llmrouter_xds_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmrouter_xds_proto_rawDesc), len(file_llmrouter_xds_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmrouter_xds_proto_goTypes,
		DependencyIndexes: file_llmrouter_xds_proto_depIdxs,
		MessageInfos:      file_llmrouter_xds_proto_msgTypes,
	}.Build()
	File_llmrouter_xds_proto = out.File
	file_llmrouter_xds_proto_goTypes = nil
	file_llmrouter_xds_proto_depIdxs = nil
}
