apiVersion: tenant.llm-router.example.io/v1alpha1
kind: TenantPipeline
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tenantpipeline-sample
spec:
  # TODO(user): Add fields here
