name: Build and Push to ACR

on:
  push:
    branches: [ master ]

permissions:
  id-token: write   # 必须打开，才能请求 OIDC token
  contents: read

jobs:
  # === Job 1: lint & fmt ===
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [operator, dataplane]
    steps:          
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.5'
          working-directory: ${{ matrix.directory }}
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          working-directory: ${{ matrix.directory }}

      - name: Check go fmt
        working-directory: ${{ matrix.directory }}
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not formatted in ${{ matrix.directory }}. Please run 'go fmt'."
            exit 1
          fi

      - name: Run go vet
        working-directory: ${{ matrix.directory }}
        run: go vet ./...
  # === Job 2: 单元测试 (并行执行) ===
  test:
    name: Unit Tests (${{ matrix.directory }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [operator, dataplane]
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.5'
          working-directory: ${{ matrix.directory }}

      - name: Run Test
        working-directory: ${{ matrix.directory }}
        run: |
          if [ "${{ matrix.directory }}" = "operator" ]; then
            make test
          else
            go test -v -race -coverprofile=coverage.out ./...
          fi
# === Job 3: build scan & push image 
  build-scan-push:
    name: Build & Trivy Scan
    runs-on: ubuntu-latest
    needs: [lint, test] # 核心逻辑：需要 lint 和 test 都成功后才执行
    permissions:
      id-token: write   # 必须打开，才能请求 OIDC token
      contents: read
    strategy:
      matrix:
        directory: [operator, dataplane]
    env:
      ACR_REGISTRY: registry.${{ vars.ACR_REGION }}.aliyuncs.com 
      # CONTROLLER_IMAGE_NAME: ${{ vars.ACR_NAMESPACE }}/${{ vars.TEST_IMAGE_NAME }}
      # ${{ vars.ACR_NEWVERSION_REGISTRY }}/${{ vars.ACR_NAMESPACE }}/${{ matrix.directory }}:${{ github.sha }}
      # IMAGE: ${{ vars.ACR_NEWVERSION_REGISTRY }}/${{ vars.ACR_NAMESPACE }}/${{ matrix.directory }}:${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set short git commit SHA
        run: |
          caculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHA_SHORT=$caculatedSha" >> $GITHUB_ENV
      
      # - name: Configure Alibaba Cloud credentials (OIDC)
      #   uses: aliyun/configure-aliyun-credentials-action@v1
      #   # reference document: https://github.com/aliyun/configure-aliyun-credentials-action
      #   with:
      #     # 和 RAM OIDC IdP 的 Client ID 保持一致
      #     role-to-assume: ${{ vars.ALIYUN_ROLE_NAME }} # RAM Role
      #     oidc-provider-arn: ${{ vars.ALIYUN_OIDC_PROVIDER_ARN }} # PROVIDER OIDC
      #     audience: ${{ vars.ALIYUN_STS_AUDIENCE }}
      #     role-session-expiration: 1800  # 会话过期时间
      #     role-session-name: 'github-action-session'  # 会话名称
      


      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker Image (Locally)
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.directory }}
          file: ./${{ matrix.directory }}/Dockerfile
          push: false
          tags: ${{ vars.ACR_NEWVERSION_REGISTRY }}/${{ vars.ACR_NAMESPACE }}/${{ matrix.directory }}:${{ env.COMMIT_SHA_SHORT }}
          outputs: type=docker,dest=/tmp/${{ matrix.directory }}.tar # 导出镜像文件供Trivy使用

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: /tmp/${{ matrix.directory }}.tar # 扫描刚才导出的镜像
          format: 'table'
          exit-code: '1' # 发现漏洞则失败
          severity: 'CRITICAL,HIGH' # 只关注高危和严重漏洞
      
      - name: Login to ACR
        uses: aliyun/acr-login@v1 
        with:
          # 直接指定你的 ACR 注册表地址, 以及相关的STS Token的相关身份凭证参数
          login-server: ${{ env.ACR_NEWVERSION_REGISTRY }}
          # access-key-id: ${{ env.ALIBABA_CLOUD_ACCESS_KEY_ID }}
          # access-key-secret: ${{ env.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
          # security-token: ${{ env.ALIBABA_CLOUD_SECURITY_TOKEN }}
          # region-id: ${{ vars.ACR_REGION }}
          # instance-id: ${{ vars.ACR_INSTANCE_ID }}
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"
      
      - name: Load image back to Docker
        run: docker load -i /tmp/${{ matrix.directory }}.tar

      - name: push image
        # 注意docker build的格式: -t <tag> -f <dockerfilePath> .<BuildContext>
          # docker build -t ${{ vars.ACR_NEWVERSION_REGISTRY }}/${{ vars.ACR_NAMESPACE }}/${{ matrix.directory }}:${{ env.COMMIT_SHA_SHORT }} -f ./${{ matrix.directory }}/Dockerfile  ./${{ matrix.directory }}
        run: |
          docker push ${{ vars.ACR_NEWVERSION_REGISTRY }}/${{ vars.ACR_NAMESPACE }}/${{ matrix.directory }}:${{ env.COMMIT_SHA_SHORT }}
